# Generated by Django 5.0.14 on 2025-12-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_ai_category_confidence_expense_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or occupation', null=True),
        ),
    ]
