# Generated by Django 5.0.14 on 2025-12-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_source_file_income_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
